'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Chip8.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _15PUZZLE() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_15PUZZLE", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property _15PUZZLE1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_15PUZZLE1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property BLINKY() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("BLINKY", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property BLINKY1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("BLINKY1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property BLITZ() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("BLITZ", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property BREAKOUT() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("BREAKOUT", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property BREAKOUT1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("BREAKOUT1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property BRIX() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("BRIX", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property BRIX1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("BRIX1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property CONNECT4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CONNECT4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property GUESS() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("GUESS", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property HIDDEN() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("HIDDEN", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property HIDDEN1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("HIDDEN1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property invaders() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("invaders", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property INVADERS1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("INVADERS1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property KALEID() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("KALEID", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property MAZE() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MAZE", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property MAZE1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MAZE1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property MERLIN() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MERLIN", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property MISSILE() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MISSILE", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PONG() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PONG", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PONG1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PONG1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property pong2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("pong2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PONG21() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PONG21", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PUZZLE() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PUZZLE", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property SQUASH() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SQUASH", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property SYZYGY() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SYZYGY", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property SYZYGY1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SYZYGY1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property TANK() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("TANK", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property tetris() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("tetris", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property TICTAC() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("TICTAC", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property UFO() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("UFO", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property UFO1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("UFO1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property VBRIX() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("VBRIX", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property VBRIX1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("VBRIX1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property VERS() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("VERS", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property WALL() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("WALL", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property WIPEOFF() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("WIPEOFF", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
